version: 1.0.{build}
configuration: release

#restore NuGet packages before running MSBuild
before_build:
  - appveyor DownloadFile "https://dist.nuget.org/win-x86-commandline/v3.5.0-beta2/NuGet.exe"
  - nuget restore
shallow_clone: true
build:
  publish_wap: true
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
deploy:
- provider: WebDeploy
  server: https://s2kdesign-001-site12.ctempurl.com:8172/msdeploy.axd
  website: s2kdesign-001-site12
  username: ifc\s2kdesign-001
  password:
    secure: 824HCV6mH43c4kkXO5QaOA==
  aspnet_core: true
  app_offline: true
  sync_retry_attempts: 2
  sync_retry_interval: 1000
  aspnet_core_force_restart: true
  on:
    branch: master
