version: 1.0.{build}
configuration: release

#restore NuGet packages before running MSBuild
before_build:
  - appveyor DownloadFile "https://dist.nuget.org/win-x86-commandline/v3.5.0-beta2/NuGet.exe"
  - nuget restore
shallow_clone: true
build:
  publish_wap_xcopy: true
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
artifacts:
- path: build\_PublishedWebsites\Website_Package\Website.zip
  name: WebsitePackage
deploy:
- provider: WebDeploy
  server: https://s2kdesign-001-site12.ctempurl.com:8172/msdeploy.axd
  website: s2kdesign-001-site12
  username: ifc\s2kdesign-001
  password:
    secure: 824HCV6mH43c4kkXO5QaOA==
  aspnet_core: true
  aspnet_core_force_restart: true
  on:
    branch: master
